name: plumbing
version: 0.1.0
author: Owen Shepherd <*@owenshepherd.net>
description: Dart toolkit for Pump.io connected applications
homepage: https://github.com/oshepherd/plumbing.dart
dependencies:
  alchemy: '>=0.1.0 <0.2.0'
  browser: '>=0.10.0 <0.11.0'
  hubsubbable: '>=0.1.0 <0.2.0'
  oauth: '>=0.2.0 <0.3.0'
  page_templates:
    git: https://github.com/oshepherd/page_templates.dart.git
  path: '>=1.1.0 <2.0.0'
  shelf: '>=0.5.0 <0.6.0'
  shelf_route: '>=0.5.0 <0.6.0'
  uri: '>=0.9.0 <0.10.0'
